### ISSUE TITLE
sh: optionally do not filter the current pane

### ISSUE THREAD

**Issue by blueyed** [wellle/tmux-complete.vim#54]
I'd like to use the shell script for the zsh completion method described in http://blog.plenz.com/2012-01/zsh-complete-words-from-tmux-pane.html / https://gist.github.com/blueyed/6856354, and that includes especially the current pane.

Maybe passing in the list of panes (`$_tmux_panes`) could be an option?

**Comment by wellle** [comment]
I understand. But I would probably prefer to add an argument to specify the pane selection strategy instead of outsourcing the implementation to the caller. Strategies could include:

Current pane
Current window
Current window without current pane
Current session (without current pane)
All sessions (without current pane)

That could be modeled by something like pane scope and a flag to skip the current pane.  

Sounds good?

**Comment by blueyed** [comment]
Sounds good.

While at it, this might be a good time to move from positional arguments to options maybe?

**Comment by wellle** [comment]
Totally.
